### ISSUE TITLE
training details

### ISSUE THREAD

**Issue by sansanfree** [wencheng256/SiamBAN-ACM#3]
could u provide more details about training? including config.yaml and the settings of training datasets? I re-produced the training following the SiamBAN, but the results are far from your listed results.

 I see your provided config.yaml which has the '/raid/dxp/wencheng/siamACBan/experiments/siamacban.pth',  does it means that your training has the two-stage process?

**Comment by wencheng256** [comment]
Thanks for your attention.  Our team still have some subsequent works based on this are ongoing, so that we only release inference code before they are finished.
We didn't use a two-stage process and the config mentioned belongs to our subsequent experiment,  we just modify the hyper-parameter and forgot to remove other configs. Thank you for your noticing on this, and I will modify the configs and remove this unrelated information.

I'll remove your comment for there is private information like absolute path. Please forgive me.
